### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by edunham** [edunham/vcttools-cinnabar#1]
- [ ] update readme to reflect homu integration
- [ ] test and fix up postgres migrations & queries
- [ ] calls to hg <-> git conversion
- [ ] additional db tables to track paired hg commit
- [ ] expand kicking off tests to include TC try push
- [ ] expand reading test results to include TC results from treeherder
- [ ] figure out proper versions of new deps and pin them in requirements.txt
